### ISSUE TITLE
Outdated default channel

### ISSUE THREAD

**Issue by corvus-ch** [appuio/component-openshift4-version#5]
This component defines `stable-4.4` as the update channel. New clusters get setup up with version 4.8. As a result, the cluster version operator is complaining.

## Steps to Reproduce the Problem

1. Set up a cluster according to https://kb.vshn.ch/oc4/how-tos/cloudscale/install.html (or on Exoscale).
2. Check Administration -> Cluster Settings in the web console

## Actual Behavior
* Update channel is set to `stable-4.4`
* Last installed version is `4.8.*`
* Cluster version operator is complaining about version not found in channel.

## Expected Behavior
* The update channel matches the installed version

**Comment by mhutter** [comment]
See #4
